### PR TITLE
Updating exec usage

### PR DESCRIPTION
**Pull request by dakerfp**
It was not working on python 2.7

### CODE REVIEW

**Comment by Suor** [comment]
Tested exec statement in python 2.7.4 - works fine. 

Your chatterbot test raises an error though. Both with exec statement and exec function.

**Comment by Suor** [comment]
Last commits should fix issues with chatterbot

**Comment by dakerfp** [comment]
Which python version are you using?

2013/9/28 Alexander Schepanovski notifications@github.com

> Last commits should fix issues with chatterbot
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Suor/patterns/pull/4#issuecomment-25290125
> .

## 

Daker Fernandes Pinheiro
http://codecereal.blogspot.com

**Comment by Suor** [comment]
2.7.4

**Comment by dakerfp** [comment]
Did you applied all the patches? Or only added the test case?

**Comment by Suor** [comment]
I did it both ways
02 ÏËÔ. 2013 Ç. 22:20 ÐÏÌØÚÏ×ÁÔÅÌØ "Daker Fernandes Pinheiro" <
notifications@github.com> ÎÁÐÉÓÁÌ:

**Comment by dakerfp** [comment]
Weird. :-(
Could you please paste the traceback?

**Comment by Suor** [comment]
Why? Doesn't latest github version work for you?

**Comment by dakerfp** [comment]
No it doesn't because the exec statement was deprecated. So I made a patch to use the function instead.
You last commit (0ffa59604f9e127cda76f81bc1743eb294b6d38a) also broke it, because  you did not added the assign into the function body.

**Comment by Suor** [comment]
Do you run python 3? Because exec statement is not deprecated in python 2.

I also don't get that about assign not added to function body. Everything works as intended here in python 2.7 and all tests pass including your depth and chatterbot.

**Comment by Suor** [comment]
Maybe you can post your test results (with your tests and latest github version of patterns)?

**Comment by dakerfp** [comment]
Now it works. Thanks!
Do you need some help/functionality/refactoring as a contribution?

**Comment by Suor** [comment]
I don't really need something, but if you can come up with something useful when you are welcome.

**Pull request closed without merging**
